# docker-compose.yml
version: '3'

services:
  app1:
    build: ./app1
    ports:
      - "8001:80"

  app2:
    build: ./app2
    ports:
      - "8002:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
